export const RETURN_REQUEST_STATUS = {
  REQUESTED: 'REQUESTED',
  PENDING_INSPECTION: 'PENDING_INSPECTION',
  INSPECTED: 'INSPECTED',
}

export const ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
}

export const ASSET_FINAL_STATUS = {
  AVAILABLE: 'AVAILABLE',
  MAINTENANCE: 'MAINTENANCE',
  BROKEN: 'BROKEN',
}

export const HANDBACK_CONDITION = {
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  DAMAGED: 'DAMAGED',
  MISSING_ACCESSORIES: 'MISSING_ACCESSORIES',
  BROKEN: 'BROKEN',
}
