export const REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  ASSIGNED: "ASSIGNED",
  REJECTED: "REJECTED"
}

export const REQUEST_URGENCY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL"
}
